### PR TITLE
Disable support for SSLv2/3

### LINKED ISSUE #24: Disable SSLv2/3
The transport adapter that is currently being used [enables SSLv2 and SSLv3](https://github.com/ChannelFinder/pyCFClient/blob/master/channelfinder/ChannelFinderClient.py#L734). Note that these protocol versions are considered insecure since years ([RFC6176](https://tools.ietf.org/html/rfc6176), [POODLE](https://en.wikipedia.org/wiki/POODLE)). In general enabling protocols that are not supported by the underlying libraries by default anymore doesn't sound like a good idea to me.

### PR DESCRIPTION
**Pull request by mark0n**
This fixes #24.

### CODE REVIEW

**Comment by mark0n** [comment]
The failing test doesn't seem to be related to my change.

**Comment by shroffk** [comment]
yes, that is fine...the error is due to the absence of the .travis file

**Comment by shroffk** [comment]
were you able to successfully use the client with the channelfinder service.

**Comment by mark0n** [comment]
I wasn't able to test with `master` due to some unrelated changes which broke it (at least for my environment). But using a slightly older version (cccf67b1867b830660a8c6bbb8e1f6368c2a8c80), I was able to verify that my change works (connects fine, I get the expected result).

**Comment by shroffk** [comment]
Ok great, 
I will merge this then

**Pull request merged**
