### PR TITLE
Add support for the scroll API in channelfinder. Closes #30

### LINKED ISSUE #30: Add support for fetching channels using the scroll API.

### PR DESCRIPTION
**Pull request by iTerminate**

### CODE REVIEW

**Comment by jacomago** [comment]
@iTerminate Is there a reason you want to used the scroll api? We have discussed removing it since the main search api has more capabilities.

**Comment by iTerminate** [comment]
It's been a while but if I remember correctly the search is limited to only 10k results and there is no way to paginate to the next set of results. I use the scroll API to get complete list of results. I remember reading that some settings may be tweaked in elasticsearch to increase that number but if the number of results is unknown this is not helpful.

**Comment by jacomago** [comment]
@iTerminate you can paginate now with the elastic parameter "search_after", which is passed in the query to elastic. See https://www.elastic.co/guide/en/elasticsearch/reference/8.13/paginate-search-results.html#search-after for how it works.

**Comment by iTerminate** [comment]
Ahh, sounds good. I agree then lets drop scroll API and have a better search. Thank you!

**Comment by shroffk** [comment]
@iTerminate is it ok if I close this PR since we are using `search_after`

**Comment by iTerminate** [comment]
Yes, I can migrate my code to use `search_after` in the future.

**Pull request closed without merging**
